---
name: Build STL files
on:
  - pull_request
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y freecad freebsd-buildutils

      - name: Build STL files
        run: |
          fmake
          ls *.stl
